import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/base/Navbar";
import Footer from "@/components/base/Footer";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "PaperTheory",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        {children}
        <Footer />
        
        {/* Floating GENZ Button */}
        <Link href="/genz" className="fixed bottom-4 left-1/2 transform -translate-x-1/2 bg-neutral-900 text-white px-8 py-2 rounded-full shadow-lg hover:bg-neutral-800 transition z-50 animate-bounce">
          GENZ →
        </Link>
      </body>
    </html>
  );
}
